name: Link Checker
on:
  push:
    branches:
      - master
    paths:
      - README.md

jobs:
  generate:
    name: Advocate Trends Link Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Update readme
        uses: ./

      - name: Commit results
          run: |
            git commit README.md -m 'Re-build README.md' || echo "No changes to commit"
            git push origin || echo "No changes to commit"