name: Link Checker
on:
  push:
    branches:
      - master
jobs:
  generate:
    name: Advocate Trends Link Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
        
             fetch-depth: 0
      - name: Update readme

        uses: ./
      - name: readme
        uses: actions/upload-artifact@v2
        with:
            name: readme
            path: /home/runner/work/_temp/_github_home/README.md

  upload:
    name: Upload Readme to PR
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Download results from the generate job
        uses: actions/download-artifact@v2
        with:
            name: readme
      - name: Add artifact to repo
        run: |
          # change John Doe with the name you want to display
          git config --global user.name "Shayne Boyer"
          # change @[john.doe] with your @[username]
          git config --global user.email "spboyer@live.com"
          git add --all
          git push